[build]
base = "client/"
publish = "client/build/"
command = "yarn build"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "null"
  to = "/index.html"
  status = 200

  # A basic redirect rule
[[redirects]]
  from = "/callback*"
  to = "/callback"